name: Release
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java: [ 'openjdk@1.17' ]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}

      - name: Set current version
        id: version
        shell: bash
        run: |
          sbt 'cli/writeVersion'
          KEEPER_VERSION=$(cat target/version.txt)
          echo "KEEPER_VERSION=${KEEPER_VERSION}" >> $GITHUB_ENV

          if [ -z "${KEEPER_VERSION}" ]; then
            echo "Version not set!"
            exit 1
          fi

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: modules/webview

      - name: create zip package
        run: ./make-cli.sh

      - name: Publish Release (${{ env.KEEPER_VERSION }})
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: modules/cli/target/universal/keeper-cli-${{ env.KEEPER_VERSION }}.zip
      - name: Publish Pre-Release
        uses: ncipollo/release-action@v1
        if: ${{ github.ref }} == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allowUpdates: true
          tag: "nightly"
          commit: "main"
          body: "Floating tag associating the latest build from the main branch"
          name: "keeper nightly"
          replacesArtifacts: true
          removeArtifacts: true
          artifacts: modules/cli/target/universal/keeper-cli-${{ env.KEEPER_VERSION }}.zip
